FROM quay.io/centos/centos:stream9

ENV PBR_VERSION 14.0.0
ENV LOG_FILE /var/log/{{ logs_volume_name }}/{{ logs_volume_name }}.log

RUN  yum install -y git python3-pip \
    gcc gcc-c++ openssl-devel libffi-devel \
    libxml2-devel libxslt-devel zlib-devel bzip2-devel

#creating canary user
RUN  groupadd --gid {{ health_check_gid }} {{ health_check_group }} \
    && useradd -l -M --shell /usr/sbin/nologin --uid {{ health_check_uid }} --gid {{ health_check_gid }} --no-create-home {{ health_check_user }}

#log location
RUN mkdir -p /var/log/{{ logs_volume_name }}
RUN touch /var/log/{{ logs_volume_name }}/{{ logs_volume_name }}.log
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} /var/log/{{ logs_volume_name }}

#get required repos
RUN mkdir {{ cloud_volume_name }}
RUN cd {{ cloud_volume_name }} && git clone https://github.com/stackhpc/HealthMonitorTempestPlugin
RUN cd {{ cloud_volume_name }} && git clone https://github.com/stackhpc/temp-tempest-pythonconf python-tempestconf
RUN cd {{ cloud_volume_name }} && git clone https://github.com/stackhpc/tempest-fork
#get latest 
RUN cd {{ cloud_volume_name }}/tempest-fork/ && git checkout no_admin_creds && git pull 
RUN cd {{ cloud_volume_name }}/python-tempestconf/ && git checkout master && git pull 
RUN cd {{ cloud_volume_name }}/HealthMonitorTempestPlugin/ && git checkout main && git pull
#install 
RUN pip3 install {{ cloud_volume_name }}/tempest-fork/
RUN pip3 install {{ cloud_volume_name }}/python-tempestconf/
RUN pip3 install {{ cloud_volume_name }}/HealthMonitorTempestPlugin/

#tempest workspace
RUN cd {{ cloud_volume_name }} && tempest init cloud
RUN touch {{ cloud_volume_name }}/cloud/etc/accounts.yml
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} {{ cloud_volume_name }}
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} /tmp/tempest-lock

#cron stuff 
RUN mkdir -p {{ cron_lock_dir }} && touch {{ cron_lock_dir }}/cron.lock
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} {{ cron_lock_dir }} 

# workaround for `dubious ownership`
RUN git config --global --add safe.directory '*'

USER {{ health_check_user }}