FROM quay.io/centos/centos:stream9

ENV PBR_VERSION 14.0.0
ENV LOG_FILE /var/log/{{ logs_volume_name }}/{{ logs_volume_name }}.log

RUN  yum install -y git python3-pip \
    gcc gcc-c++ openssl-devel libffi-devel \
    libxml2-devel libxslt-devel zlib-devel bzip2-devel

#creating canary user
RUN  groupadd --gid {{ health_check_gid }} {{ health_check_group }} \
    && useradd -l -M --shell /usr/sbin/nologin --uid {{ health_check_uid }} --gid {{ health_check_gid }} {{ health_check_user }}

#log location
RUN mkdir -p /var/log/{{ logs_volume_name }}
RUN touch /var/log/{{ logs_volume_name }}/{{ logs_volume_name }}.log
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} /var/log/{{ logs_volume_name }}

#moving stuff to home dir 
COPY . /home/{{ health_check_user }}
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} /home/{{ health_check_user }}

#tempest stuff install
RUN cd /home/{{ health_check_user }} && git submodule init && git submodule update
#get latest 
RUN cd /home/{{ health_check_user }}/tempest-fork/ && git branch master && git pull 
RUN cd /home/{{ health_check_user }}/python-tempestconf/ && git branch master && git pull 
RUN cd /home/{{ health_check_user }}/HealthMonitorTempestPlugin/ && git branch master && git pull
#install 
RUN pip3 install /home/{{ health_check_user }}/tempest-fork/
RUN pip3 install /home/{{ health_check_user }}/python-tempestconf/
RUN pip3 install /home/{{ health_check_user }}/HealthMonitorTempestPlugin/

#tempest workspace
RUN tempest init {{ cloud_volume_name }}
RUN touch {{ cloud_volume_name }}/etc/accounts.yml
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} {{ cloud_volume_name }}
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} /tmp/tempest-lock

#cron stuff 
RUN mkdir -p {{ cron_lock_dir }} && touch {{ cron_lock_dir }}/cron.lock
RUN chown -R {{ health_check_uid }}:{{ health_check_gid }} {{ cron_lock_dir }} 

USER {{ health_check_user }}